#!/bin/bash
# Demo script showing how to use the git time-travel tools
# This script demonstrates the workflow without making actual changes

echo "========================================"
echo "Git Time Travel Demo"
echo "========================================"
echo ""
echo "This demo shows how to use the time-travel scripts safely."
echo ""

# Step 1: View history
echo "Step 1: View commit history"
echo "----------------------------"
echo "Command: ./scripts/view-history.sh -n 5"
echo ""
./scripts/view-history.sh -n 5
echo ""

# Step 2: Show how to create backup
echo ""
echo "Step 2: ALWAYS create a backup first"
echo "-------------------------------------"
echo "Before reverting, you should ALWAYS create a backup branch:"
echo ""
echo "  git branch backup-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "This creates a branch like: backup-20251121-145000"
echo ""

# Step 3: Show revert options
echo ""
echo "Step 3: Choose a revert method"
echo "-------------------------------"
echo ""
echo "Four methods available:"
echo ""
echo "1. SOFT (--soft)"
echo "   ✓ Safest option for beginners"
echo "   ✓ Keeps all changes staged"
echo "   ✓ You can review before committing"
echo "   Example: ./scripts/revert-to-date.sh bbca881 --soft"
echo ""
echo "2. MIXED (--mixed, default)"
echo "   ✓ Keeps changes but unstaged"
echo "   ✓ Good for selective commit"
echo "   Example: ./scripts/revert-to-date.sh bbca881 --mixed"
echo ""
echo "3. REVERT (--revert)"
echo "   ✓ Creates new commits to undo"
echo "   ✓ Preserves history"
echo "   ✓ BEST for shared branches"
echo "   Example: ./scripts/revert-to-date.sh bbca881 --revert"
echo ""
echo "4. HARD (--hard)"
echo "   ⚠️  DANGEROUS! Deletes all changes"
echo "   ⚠️  Cannot be undone easily"
echo "   ⚠️  Use only if absolutely sure"
echo "   Example: ./scripts/revert-to-date.sh bbca881 --hard"
echo ""

# Step 4: Show date format options
echo ""
echo "Step 4: Date format options"
echo "---------------------------"
echo ""
echo "You can specify the target in multiple ways:"
echo ""
echo "  By commit hash:     bbca881"
echo "  By full date:       '2025-11-21 11:00:00'"
echo "  By date only:       '2025-11-20'"
echo "  By relative time:   '2 days ago'"
echo "  By relative commit: 'HEAD~5' (5 commits back)"
echo ""

# Step 5: Show recovery options
echo ""
echo "Step 5: If something goes wrong"
echo "--------------------------------"
echo ""
echo "Don't panic! You can undo with git reflog:"
echo ""
echo "  1. View reflog:        git reflog"
echo "  2. Find previous HEAD: Look for HEAD@{1} or similar"
echo "  3. Restore:            git reset --hard HEAD@{1}"
echo ""
echo "Or use your backup branch:"
echo ""
echo "  git checkout backup-20251121-145000"
echo ""

# Step 6: Example workflow
echo ""
echo "Step 6: Example workflow"
echo "------------------------"
echo ""
echo "Complete example:"
echo ""
echo "  # 1. View history to find target"
echo "  ./scripts/view-history.sh"
echo ""
echo "  # 2. Create backup"
echo "  git branch backup-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "  # 3. Revert (using soft reset)"
echo "  ./scripts/revert-to-date.sh bbca881 --soft"
echo ""
echo "  # 4. Review changes"
echo "  git status"
echo "  git diff --staged"
echo ""
echo "  # 5. If happy, commit the revert"
echo "  git commit -m 'Revert to previous state'"
echo ""
echo "  # 6. If not happy, undo"
echo "  git reset --hard HEAD@{1}"
echo ""

echo ""
echo "========================================"
echo "Ready to try it yourself?"
echo "========================================"
echo ""
echo "Remember:"
echo "  1. ALWAYS create a backup first"
echo "  2. Start with --soft to be safe"
echo "  3. Review changes before committing"
echo "  4. Use --revert for shared branches"
echo ""
echo "Need help? Run: ./scripts/revert-to-date.sh --help"
echo ""
